[tool.isort]
line_length = 120
known_first_party = "drf_spectacular,tests"
known_third_party = "rest_framework_simplejwt,rest_polymorphic,polymorphic,oauth2_provider,django,rest_framework,djstripe,rest_framework_jwt"
multi_line_output = 3
use_parentheses = true
include_trailing_comma = true
